# Generated by Django 3.0.6 on 2020-05-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20200530_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myadmin',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='myadmin',
            old_name='title',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='myadmin',
            name='timestamp',
        ),
    ]
