# Generated by Django 3.0.6 on 2020-05-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_auto_20200530_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='myadmin',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
